In [0]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.utils import to_categorical
# Import `Sequential` from `keras.models`
from tensorflow import keras
from keras.models import Sequential

# Import `Dense` from `keras.layers`
from keras.layers import Dense

from sklearn import preprocessing,metrics



In [187]:
print(tf.__version__)

2.1.0


In [0]:
tf.random.set_seed(42)

In [0]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()

In [190]:
pwd

'/content'

In [191]:
ls

bank.csv  sample_data/


In [192]:
bank_df = pd.read_csv('bank.csv')
bank_df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [193]:
bank_df.shape

(10000, 14)

In [194]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [195]:
bank_df.tail()

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[5 rows x 14 columns]

In [196]:
pd.value_counts(bank_df['Geography'])

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [0]:
bank_df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True) #Drop columns that are not required 

In [198]:
bank_df.shape

(10000, 11)

In [0]:
#Convert categorical String cols to numeric
le = preprocessing.LabelEncoder()
bank_df['Geography'] = le.fit_transform(bank_df['Geography'])

In [0]:
bank_df['Gender'] = le.fit_transform(bank_df['Gender'])

In [201]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
CreditScore        10000 non-null int64
Geography          10000 non-null int64
Gender             10000 non-null int64
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9)
memory usage: 859.5 KB


In [202]:
bank_df.head()

CreditScore  Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619          0       0  ...               1        101348.88       1
1          608          2       0  ...               1        112542.58       0
2          502          0       0  ...               0        113931.57       1
3          699          0       0  ...               0         93826.63       0
4          850          2       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [0]:
cols = bank_df.columns

In [204]:
cols[:-1]

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [0]:
#Distinguish Feature and Target set
X = bank_df[cols[:-1]]
y = bank_df['Exited']

In [206]:
X.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [207]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [0]:
#Convert features and labels to numpy array
X = X.values
y=y.values
X = X.astype('float32')
y = y.astype('int32')

In [209]:
X

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [6.0800000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [5.0200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085578e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888523e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190781e+04]], dtype=float32)

In [210]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int32)

In [0]:
#Split the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [0]:
#Normalize features
X_train  = tf.math.l2_normalize(X_train,axis=None,epsilon=1e-12,name=None)
X_test  = tf.math.l2_normalize(X_test,axis=None,epsilon=1e-12,name=None)

In [213]:
X_train

<tf.Tensor: shape=(7500, 10), dtype=float32, numpy=
array([[5.1058963e-05, 0.0000000e+00, 7.5867703e-08, ..., 0.0000000e+00,
        7.5867703e-08, 1.5980554e-03],
       [6.4487547e-05, 7.5867703e-08, 7.5867703e-08, ..., 7.5867703e-08,
        0.0000000e+00, 2.4145534e-03],
       [5.5004086e-05, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 4.6526953e-03],
       ...,
       [5.5762761e-05, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 6.9965287e-03],
       [5.0603758e-05, 0.0000000e+00, 7.5867703e-08, ..., 7.5867703e-08,
        0.0000000e+00, 7.3977108e-03],
       [5.2879790e-05, 7.5867703e-08, 7.5867703e-08, ..., 7.5867703e-08,
        7.5867703e-08, 4.0650782e-03]], dtype=float32)>

In [0]:
# Initialize the constructor
model = tf.keras.Sequential()

In [0]:
# Add input layers 
total_features = len(cols[:-1])
model.add(tf.keras.layers.Dense(total_features+1, activation='relu', input_shape=(total_features,)))
model.add(tf.keras.layers.Dense(total_features+1, activation='relu'))
#model.add(tf.keras.layers.Dense(total_features, activation='relu'))
#model.add(tf.keras.layers.Dense(total_features, activation='relu'))



In [0]:
#Output layer
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [0]:
adam  = tf.keras.optimizers.Adam(learning_rate=0.03)
model.compile(loss='binary_crossentropy',
              optimizer='adam',
          metrics=['accuracy'])

In [218]:
history = model.fit(X_train, y_train,epochs=5, batch_size=1, verbose=1)

Train on 7500 samples
Epoch 1/5
7500/7500 [==============================] - 11s 1ms/sample - loss: 0.5115 - accuracy: 0.7947
Epoch 2/5
7500/7500 [==============================] - 11s 1ms/sample - loss: 0.5079 - accuracy: 0.7947
Epoch 3/5
7500/7500 [==============================] - 11s 1ms/sample - loss: 0.5078 - accuracy: 0.7947
Epoch 4/5
7500/7500 [==============================] - 11s 1ms/sample - loss: 0.5062 - accuracy: 0.7947
Epoch 5/5
7500/7500 [==============================] - 11s 1ms/sample - loss: 0.5060 - accuracy: 0.7947


In [219]:
y_pred = np.round(model.predict(X_test))
score = model.evaluate(X_test, y_test,verbose=1)

print(score)

2500/2500 [==============================] - 0s 59us/sample - loss: 0.5003 - accuracy: 0.8012
[0.5003259104728699, 0.8012]


In [220]:
metrics.confusion_matrix(y_test, y_pred)

array([[2003,    0],
       [ 497,    0]])